export const WALLET_SELECT_WARNING = 'Por favor, selecione um proprietário e uma carteira.';
export const API_LOADING_ERROR = 'Erro ao carregar os dados.';
export const EMPTY_DATA_WARNING = 'Nenhum dado disponível';
export const WALLET_ADD_SUCCESS = 'Carteira adicionada com sucesso.';
export const WALLET_ADD_ERROR = 'Erro ao adicionar carteira.';
export const OPERATION_SELECT_WARNING = 'Por favor, selecione um propietário.'
export const OPERATION_DELETED_SUCCESSFULLY = 'Operação deletada com sucesso.';
export const OPERATION_DELITION_ERROR = 'Erro ao deletar operação.';
export const OPERATION_UPDATE_ERROR = 'Erro ao atualizar ordem operação.';
export const ERROR_ADDING_NEW_OPERATION = 'Erro ao adicionar nova operação.';